version: '3'

services:
  # App 
  app:
    container_name: app
    restart: on-failure
    image: golang:api
    build: .
    ports:
      - 8081:8081
    networks:
      - main_network
    depends_on:
      - db
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_golang
      MYSQL_USER: golang
      MYSQL_PASSWORD: golang
    networks:
      - main_network
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - main_network
networks:
  main_network:
volumes:
  db_data: